  language: java
  services:
    - mysql

  before_install:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -uroot -proot
    - sudo service mysql restart
    - mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test2;'
