  language: java
  services:
    - mysql

  before_install:
    - sudo mysql -uroot -e "USE mysql;UPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';FLUSH PRIVILEGES;"
    - sudo service mysql restart
    - mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test2;'
