  language: java
  services:
    - mysql

  before_install:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - sudo service mysql restart
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test2;'
