  language: java
  services:
    - mysql

  before_install:
    - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS test2;'
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade
    - sudo service mysql restart
    
